// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupKrRDL2z3EN-9GLpibKBXKCbMacMRPM',
    appId: '1:528031021744:web:38d249b03fac7ffa299975',
    messagingSenderId: '528031021744',
    projectId: 'tweetanalyze-1d192',
    authDomain: 'tweetanalyze-1d192.firebaseapp.com',
    storageBucket: 'tweetanalyze-1d192.appspot.com',
    measurementId: 'G-ZDEBZQNJ54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOyHjhOllNToCvxmMnvtjJfHLQHK1EMQI',
    appId: '1:528031021744:android:d6fe91241db66eab299975',
    messagingSenderId: '528031021744',
    projectId: 'tweetanalyze-1d192',
    storageBucket: 'tweetanalyze-1d192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZSQ2UHYm1V0ZZ4EHv-DeklxBXDxxk_Q',
    appId: '1:528031021744:ios:74ae84b8f4cb8e69299975',
    messagingSenderId: '528031021744',
    projectId: 'tweetanalyze-1d192',
    storageBucket: 'tweetanalyze-1d192.appspot.com',
    iosClientId: '528031021744-mfruak9msahm7ivtu483lmo4i7l60ii7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdZSQ2UHYm1V0ZZ4EHv-DeklxBXDxxk_Q',
    appId: '1:528031021744:ios:74ae84b8f4cb8e69299975',
    messagingSenderId: '528031021744',
    projectId: 'tweetanalyze-1d192',
    storageBucket: 'tweetanalyze-1d192.appspot.com',
    iosClientId: '528031021744-mfruak9msahm7ivtu483lmo4i7l60ii7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
